### ISSUE TITLE
Different Bin version

### ISSUE THREAD

**Issue by ON4BCB** [RastoH/eXtended-Coop-Controller#2]
Thank you so much for previous answer

What is the difference between the webgui.bin and xCtrl.2021.05.28o.bin version ?

I think i need to upload te xCtrl.2021.05.28o.bin to the ESP8266 ?

**Comment by RastoH** [comment]
xCtrl.2021.05.28o.bin -> firmware
webui.bin -> web ui on filesystem

https://github.com/RastoH/eXtended-Coop-Controller/blob/main/webUI/update.JPG

1. upload firmaware to esp8266 (esptol... etc)
2. connect to AP
3. go 192.168.4.1/update
4. select filesystem webui.bin -> update filesystem

**Comment by ON4BCB** [comment]
thank you,

All is working except a wifi scan in settings is giving a timeout, so unable to connect to my own wifi

any suggestions ?

**Comment by RastoH** [comment]
download & update filesystem -> webUI.bin

the old version had an error.

Sorry

**Comment by ON4BCB** [comment]
Thank you,

without hardware the wifi connection breaks every time, on a cell phone as on different Laptops,I use the D1 mini, no hardware attached

do i keep certain pins high or low ?, if connected the wifi scan give's an error every time

also saving parameters is giving a PUT error

**Comment by RastoH** [comment]
spi speed 40mhz, DIO spi mode. 

AP mode -> 10 min.
STA mode -> 5 min.

turning off after disconnect, to save batery.
