### ISSUE TITLE
WEB INTERFACE NOT FOUND

### ISSUE THREAD

**Issue by helidave** [RastoH/eXtended-Coop-Controller#3]
Hi, I thought I would try your project to look after my small flock of silkies  but I wanted to use an Adafruit Huzzah32 that I had gathering dust.  I have been able to load the binaries but cannot access the web page at 192.168.4.1.  I note the following differences between my installation and the posted version.
1) The zip file gives me xCctrl.2022.05.29a.all.bin not xCctrl.2022.05.29a.bin
2) The initial wifi zone is kurnicek-c32c99 which is also different than the one shown in the post

I have loaded the examples wifinetwork code into the Huzzah just to check if the browser link works and can confirm it does so I assume I am making a mistake when loading the bin files.  Any help would be most welcome and hello from France!
Regards
David

**Comment by RastoH** [comment]
xCCtrl is writen, compiled, tested only for **ESP8266**, Adafruit Huzah32 has core **ESP32**, _diferent_.


1. xCctrl.2022.05.29a.all.bin is firmware + filesystem
xCctrl.2022.05.29a.bin if only firmware
2.  kurnicek-xxxxxx  -> xxxxxx is device serial number
kurnicek is only preprogrammed name, can be changed via web interface

**Comment by helidave** [comment]
thanks for the response, I thought I was doing something stupid! Ive ordered the right modules and will try again when they arrive I will hopefully have more success

**Comment by helidave** [comment]
I picked up the correct esp 8266 module and loaded the xCctrl.2022.05.29a.all bin etc. as shown.  However I have the same issue, I cannot ping the 192.168.4.1 address and when I check the settings of the module I can see its connected but has no IP address - The first time the module boots I a asked for the password and enter fery1234 which gets it to connect. - Any ideas what I am doing wrong?

**Comment by RastoH** [comment]
Give me output from 192.168.4.1/info and 192.168.4.1/wifi in Acces Point mode.
What of module have you?

**Comment by helidave** [comment]
its a WeMos D1 mini Pro. With the binary files I can connect but it doesn't get an IP address so I cannot access it at all.  If I load the wifi access point example from the Arduino library then I can connect without issues and ping the  module and get the "connected " page up

**Comment by RastoH** [comment]
Test xCctrl.2022.05.31d_D1miniPro. it's dev version, compiled direct for you. 
xCctrl.2022.05.31d tested in my coop works, tested on my LOLIN D1 Mini V3.1.0 4MB and ESP8266 Witty Cloud ESP-12F WiFi Module. See firmware/ESP8266-DOWNLOAD-TOOL.png

**Comment by helidave** [comment]
Apologies for late response, my neighbour was very ill over the weekend and I had to prioritise him.  The new binaries work perfectly - thank you very much for all the effort helping me.  I will be busy building the rest of the system over the next week and hopefully upgrade my chicken coop before Christmas - really excited to install this system, it looks fantastic.
