### ISSUE TITLE
Pinouts

### ISSUE THREAD

**Issue by SThM-develop** [RastoH/eXtended-Coop-Controller#4]
Hi,
firstly congrats to great job.

I want to try this project on my coop. For sure pin numbers that you use at [pin section](https://github.com/RastoH/eXtended-Coop-Controller#pin) are from older [LOLIN D1 mini v 3.1.0](https://www.wemos.cc/en/latest/d1/d1_mini_3.1.0.html), right? Is possible to use latest version [LOLIN D1 mini v 4.0.0](https://www.wemos.cc/en/latest/d1/d1_mini.html) which one are you referring to in the main [README.md](https://github.com/RastoH/eXtended-Coop-Controller#readme)? Will be there some pin changes?

And I would also like to ask where the coop fan/heater and the LED light are connected? I couldn't find that anywhere.

Really thanks for answer.
Thomas

**Comment by RastoH** [comment]
LOLIN D1 mini boards, shields have the same pins 

Motor, LEDs are conected on motor driver -> [LOLIN v2 (tested)](https://www.wemos.cc/en/latest/d1_mini_shield/motor.html), [AT8870 Motor Shield](https://www.wemos.cc/en/latest/d1_mini_shield/at8870_motor.html), [HR8833 Motor Shield](https://www.wemos.cc/en/latest/d1_mini_shield/hr8833_motor.html)

Channel A -> door motor
CHannel B -> hen light

FAN/HEATER is in dev mode, not fully working, it uses second motor driver on i2c, i rewrite libraries to MCP230xx or PCF8574.
