### ISSUE TITLE
Motor RPM & Door timing

### ISSUE THREAD

**Issue by helidave** [RastoH/eXtended-Coop-Controller#7]
Hi,  My coop is working well now thank you.  
I just use a single motor board for the moment and have the specified 35rpm motor however, my previous system used a 12rpm motor and I quite like this as it is a little more "forgiving" on the slower chickens.  My question is: When I made a test with the slower motor the system failed because it timed out on the raise/lower timing.  Can this be extended to allow for the slower motor?

**Comment by RastoH** [comment]
upload new version xCctrl.2023.05.32o
MOTOR_MAX_RUN_TIME 40 * MILLIS_IN_SEC (40 seconds)

firmware + littlefs!

**Comment by helidave** [comment]
Okay, thanks I will try that tomorrow.  The system is working really well and the wifi Link is very solid - really pleased with it. I am very grateful you posted this, its great protection for my birds.

**Comment by helidave** [comment]
I tried the above however,  it installed without issue but it wouldn't take the connection to my LAN.  I could connect via the AP but every time I tried to add my LAN wifi it would reboot  back to AP mode.  I installed xCctrl.2022.05.32k and reduced the stroke of my door to give the slower motor time to hit the limits.

**Comment by RastoH** [comment]
xCctrl.2023.05.32oooo ?
xCctrl.2023.05.32p ?

**Comment by helidave** [comment]
xCctrl.2023.05.32o but I travel to Ireland tomorrow for work and don't return until the weekend.  For this reason I put the old firmware back in and adjusted the door limits to compensate as I needed to leave my coop in working order.

**Comment by helidave** [comment]
Im back from Ireland so will try the other binaries again this week to see if I can get it working with the 12rpm motor.  I was also wondering if its possible to drive a second motor but with just manual open/close commands. My coop has 2 sections, the main door is on the nighttime roosting area but I also have a second door which, when opened, allows the chickens to have free access to the garden area.  I wondered if it would also be possible to fit a motor to this door?

**Comment by RastoH** [comment]
We don't have any free GPIOs for reed switches, it requires redesign of WebUI, sketches

**Comment by helidave** [comment]
ah ah of course.  No worries, I will fit my old system on the external door and control it seperately - your system works flawlessly.  Its snowing here at the moment so I will have to wait for better weather to try the other binaries.

**Comment by RastoH** [comment]
check xCctrl.2023.05.32rr-dev, it is my test version that is currently running in my chicken coop.

**Comment by helidave** [comment]
Okay, will do.
I have to say your software is 100% the best I have used on my coop - it never loses connection, the time works flawlessly and its 100% reliable.
